/* eslint-disable import/extensions */
import Head from 'next/head'
import { useQuery } from '@tanstack/react-query'
import Table from 'react-bootstrap/Table'
import styles from '@/styles/Home.module.css'
import fetcher from '@/utils/fetcher'
import { SeasonSchedule } from '@/types/SeasonSchedule'
import TableRow from '@/features/table/components/TableRow'
import 'bootstrap/dist/css/bootstrap.min.css'

export default function Home() {
  const { data } = useQuery(['e'], async () =>
    fetcher<SeasonSchedule>('/api/soccer')
  )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Table striped bordered hover>
          <thead>
            <tr>
              <th>Team Names</th>
              <th>Results</th>
            </tr>
          </thead>
          <tbody>
            {data &&
              data.schedules.map((elem) => {
                return (
                  <TableRow
                    team1={elem.sport_event.competitors[0].name}
                    team2={elem.sport_event.competitors[1].name}
                    result={elem.sport_event_status}
                    key={crypto.randomUUID()}
                  />
                )
              })}
          </tbody>
        </Table>
      </main>
    </>
  )
}
